### ISSUE TITLE
Camera on but not showing anything

### ISSUE THREAD

**Issue by HatemslaH** [chenyeju295/flutter_uvc_camera#37]
I launch the sample application and click the open button, but nothing happens after that.

I get these messages in the logs, it seems that he sees the device and attaches himself to it.
```
I/flutter (22567): openUVCCamera
V/USBMonitor(22567): USBMonitor:Constructor
V/USBMonitor(22567): USBMonitor:mUsbManager=android.hardware.usb.UsbManager@3e9559b
I/MultiCameraClient(22567): register...
I/USBMonitor(22567): register:
D/TranActivityAppturboImpl(22567): onResumeHork
I/MultiCameraClient(22567): attach device name/pid/vid:/dev/bus/usb/002/014&33490&7119 
```
The preview doesn't work, and all other actions in the example don't work either.
I also tried putting different frameFormats, but it also doesn't work.

**Comment by chenyeju295** [comment]
@HatemslaH Hello, I have updated the plugin version, you can also experience the new version.

**Comment by mohitsoni2000** [comment]
Sometimes it still shows the same issue — even though I added a condition to display the 'USB not connected' screen, when I connect the USB camera, it still fails to load the camera preview.
